# Generated by Django 4.1.3 on 2022-12-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('subtitles', models.BooleanField(default=False)),
                ('production_year', models.PositiveIntegerField()),
                ('country', models.TextField()),
                ('genre', models.TextField()),
                ('fees_us', models.PositiveIntegerField(default=0)),
                ('fees_world', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('age', models.PositiveIntegerField(default=0)),
                ('rating_mpaa', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG_13'), ('R', 'R'), ('NC-17', 'NC_17')], max_length=5)),
            ],
        ),
    ]
