# Generated by Django 4.1.3 on 2022-12-12 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('subtitles', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField()),
                ('country', models.TextField()),
                ('genre', models.CharField(choices=[('Боевик', 'Боевик'), ('Приключения', 'Приключения'), ('Драма', 'Драма'), ('Фантастика', 'Фантастика'), ('Триллер', 'Триллер'), ('Детектив', 'Детектив'), ('Ужасы', 'Ужасы')], max_length=11)),
                ('fees_us', models.PositiveIntegerField(default=0)),
                ('fees_world', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('age', models.PositiveIntegerField(default=0)),
                ('rating_mpaa', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG_13'), ('R', 'R'), ('NC-17', 'NC_17')], max_length=5)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезды рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='фильм')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.ratingstar', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
