# Generated by Django 4.1.3 on 2022-12-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_artist_composer_director_producer_script_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesDubbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'Dubbing actor',
                'verbose_name_plural': 'Dubbing actors',
            },
        ),
        migrations.CreateModel(
            name='Starring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'Starring',
                'verbose_name_plural': 'Starring',
            },
        ),
        migrations.RenameModel(
            old_name='Artist',
            new_name='Painter',
        ),
        migrations.AlterModelOptions(
            name='painter',
            options={'verbose_name': 'Painter', 'verbose_name_plural': 'Painters'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='artists',
            new_name='painters',
        ),
        migrations.AddField(
            model_name='movie',
            name='roles_dubbed',
            field=models.ManyToManyField(to='movies.rolesdubbed'),
        ),
        migrations.AddField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(to='movies.starring'),
        ),
    ]
